language: python
python:
  - 3.7
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache # https://github.com/travis-ci/travis-ci/issues/5853

install:
  # Install this package and the packages listed in requirements.txt.
  - pip install .
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements.txt
  - python -m spacy download en_core_web_lg
  - python -m spacy download fr_core_news_md

script:
  - coverage run -m pytest # Run the tests and check for test coverage.
  - coverage report -m # Generate test coverage report.
  - codecov # Upload the report to codecov.
  - make -C docs html # Build the documentation.
